spring:
  application:
    name: vineeth
  config:
    activate:
      on-profile: dev
server:
  port: 9000
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: devUser
    password: devPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa.show-sql: true

logging:
  level:
    web: info